# Generated by Django 6.0.7 on 2026-09-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_academicclass_branch_department_student_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_photo',
            field=models.TextField(blank=True, default=''),
        ),
    ]
