# Generated by Django 6.0.7 on 2026-10-09 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_student_parent_email_student_parent_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='face_embedding',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='student',
            name='face_registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='face_registered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
