# Generated by Django 6.0.7 on 2026-09-23 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_academicclass_branch_department_student_section_and_more'),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableslot',
            name='academic_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_slots', to='students.academicclass'),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='year',
            field=models.IntegerField(default=1),
        ),
    ]
