# Generated by Django 6.0.7 on 2026-09-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendancerecord_options_and_more'),
        ('performance', '0002_studentscore_grade_point_subject_department_and_more'),
        ('students', '0004_student_admission_year_student_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attendancerecord',
            name='unique_student_session_attendance',
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(fields=('student', 'session'), name='unique_student_session_attendance'),
        ),
    ]
