# Generated by Django 6.0.7 on 2026-09-23 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_remove_attendancerecord_unique_student_session_attendance_and_more'),
        ('students', '0005_academicclass_branch_department_student_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='academic_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_sessions', to='students.academicclass'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='section',
            field=models.CharField(blank=True, default='A', max_length=10),
        ),
    ]
