# Generated by Django 6.0.7 on 2026-09-26 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_attendancesession_academic_class_and_more'),
        ('students', '0005_academicclass_branch_department_student_section_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='marked_via',
            field=models.CharField(choices=[('QR', 'QR Code'), ('MANUAL', 'Teacher Manual Entry'), ('LEAVE_APPROVAL', 'Approved Leave Credit')], default='MANUAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late'), ('On-Duty', 'On-Duty (OD)'), ('Medical', 'Medical Leave'), ('Excused', 'Excused Leave')], default='Present', max_length=20),
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('OD', 'On-Duty (OD)'), ('MEDICAL', 'Medical Leave'), ('CASUAL', 'Casual Leave'), ('ACADEMIC', 'Academic Duty / Symposium')], default='OD', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('document_url', models.CharField(blank=True, default='', max_length=300)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=15)),
                ('reviewer_remarks', models.CharField(blank=True, default='', max_length=300)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_leave_requests', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='students.student')),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
    ]
