# Generated by Django 6.0.7 on 2026-09-26 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_attendancerecord_marked_via_and_more'),
        ('students', '0007_student_parent_email_student_parent_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceAlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.FloatField()),
                ('attended_classes', models.IntegerField()),
                ('total_classes', models.IntegerField()),
                ('classes_needed', models.IntegerField(default=0)),
                ('threshold', models.FloatField(default=75.0)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS Text Message'), ('BOTH', 'Email & SMS')], default='BOTH', max_length=10)),
                ('student_email', models.CharField(blank=True, max_length=255)),
                ('parent_email', models.CharField(blank=True, max_length=255)),
                ('student_phone', models.CharField(blank=True, max_length=50)),
                ('parent_phone', models.CharField(blank=True, max_length=50)),
                ('email_sent', models.BooleanField(default=False)),
                ('sms_sent', models.BooleanField(default=False)),
                ('trigger_source', models.CharField(default='MANUAL', max_length=30)),
                ('message_content', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatched_attendance_alerts', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_alerts', to='students.student')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
