# Generated by Django 6.0.7 on 2026-10-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_attendancealertlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='device_fingerprint',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='is_flagged_proxy',
            field=models.BooleanField(default=False, help_text='Flagged if anti-proxy heuristics detect suspicious shared device or rapid remote IP patterns.'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='proxy_flags',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='user_agent',
            field=models.TextField(blank=True, default=''),
        ),
    ]
