# Generated by Django 6.0.7 on 2026-10-09 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_attendancerecord_device_fingerprint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='distance_meters',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='face_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='face_matched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='radius_meters',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='require_face',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='require_geo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='marked_via',
            field=models.CharField(choices=[('QR', 'QR Code'), ('QR_FACE_GEO', 'QR + Face + Geo Verified'), ('MANUAL', 'Teacher Manual Entry'), ('LEAVE_APPROVAL', 'Approved Leave Credit')], default='MANUAL', max_length=20),
        ),
    ]
