# Generated by Django 6.0.7 on 2026-09-22 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0003_alter_student_options_student_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('branch', models.CharField(default='CSE', max_length=50)),
                ('semester', models.CharField(default='1', max_length=10)),
                ('credits', models.IntegerField(default=3)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='StudentScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internals', models.FloatField(default=25.0)),
                ('end_sem', models.FloatField(default=60.0)),
                ('total', models.FloatField(default=85.0)),
                ('grade', models.CharField(default='A', max_length=10)),
                ('grade_class', models.CharField(default='grade-a', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='performance.subject')),
            ],
            options={
                'ordering': ['student', 'subject'],
                'unique_together': {('student', 'subject')},
            },
        ),
    ]
