# Generated by Django 6.0.7 on 2026-09-22 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0001_initial'),
        ('students', '0004_student_admission_year_student_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentscore',
            name='grade_point',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='subject',
            name='department',
            field=models.CharField(blank=True, default='Computer Science & Engineering', max_length=100),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='studentscore',
            name='end_sem',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='studentscore',
            name='grade',
            field=models.CharField(default='F', max_length=10),
        ),
        migrations.AlterField(
            model_name='studentscore',
            name='grade_class',
            field=models.CharField(default='grade-fail', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentscore',
            name='internals',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='studentscore',
            name='total',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Internal 1', 'Internal Assessment 1'), ('Internal 2', 'Internal Assessment 2'), ('Assignment', 'Course Assignment'), ('Mid Examination', 'Mid-Term Examination'), ('End Semester', 'End Semester Examination')], default='Internal 1', max_length=100)),
                ('max_marks', models.FloatField(default=100.0)),
                ('weightage_percent', models.FloatField(default=100.0)),
                ('semester', models.CharField(blank=True, default='1', max_length=10)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='performance.subject')),
            ],
            options={
                'ordering': ['subject', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.FloatField()),
                ('grade', models.CharField(blank=True, default='', max_length=10)),
                ('grade_point', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_marks', to='performance.assessment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='performance.subject')),
            ],
            options={
                'ordering': ['student', 'subject', 'assessment'],
                'unique_together': {('student', 'subject', 'assessment')},
            },
        ),
    ]
