# Generated by Django 6.0.7 on 2026-09-26 10:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0002_studentscore_grade_point_subject_department_and_more'),
        ('students', '0005_academicclass_branch_department_student_section_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('academic_year', models.CharField(default='2025-2026', max_length=50)),
                ('exam_type', models.CharField(choices=[('REGULAR', 'Semester End Regular Examination'), ('SUPPLEMENTARY', 'Supplementary / Backlog Examination'), ('MID_TERM', 'Mid-Term Examination'), ('INTERNAL', 'Internal Assessment Exam')], default='REGULAR', max_length=50)),
                ('branch', models.CharField(default='ALL', max_length=50)),
                ('semester', models.CharField(default='ALL', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('min_attendance_percentage', models.FloatField(default=75.0)),
                ('is_published', models.BooleanField(default=True)),
                ('instructions', models.TextField(default='1. Candidates must arrive at the examination hall at least 15 minutes before commencement.\n2. Possession of mobile phones, smartwatches, or unauthorized study material is strictly prohibited.\n3. Candidates must carry their valid College Identity Card and this printed Hall Ticket.\n4. No candidate will be admitted to the examination hall 30 minutes after the exam start time.\n5. Write your Roll Number and Paper Code clearly on the answer booklet.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ExamTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('hall_number', models.CharField(default='Main Examination Block', max_length=100)),
                ('order', models.PositiveIntegerField(default=1)),
                ('exam_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable', to='performance.examsession')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedules', to='performance.subject')),
            ],
            options={
                'ordering': ['exam_date', 'start_time'],
                'unique_together': {('exam_session', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='HallTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall_ticket_number', models.CharField(blank=True, max_length=64, unique=True)),
                ('verification_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('calculated_attendance_pct', models.FloatField(default=0.0)),
                ('is_eligible', models.BooleanField(default=True)),
                ('is_condoned', models.BooleanField(default=False)),
                ('condonation_reason', models.TextField(blank=True, default='')),
                ('condoned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('condoned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='condoned_hall_tickets', to=settings.AUTH_USER_MODEL)),
                ('exam_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hall_tickets', to='performance.examsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hall_tickets', to='students.student')),
            ],
            options={
                'ordering': ['exam_session', 'student__roll_no'],
                'unique_together': {('exam_session', 'student')},
            },
        ),
    ]
