# Generated by Django 6.0.7 on 2026-09-26 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0004_examsession_approved_at_examsession_approved_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hallticket',
            name='is_verified_in_hall',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hallticket',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_hall_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hallticket',
            name='verified_in_hall_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
