# Generated by Django 6.0.7 on 2026-09-27 04:18

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0007_student_parent_email_student_parent_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_mandatory_for_exam', models.BooleanField(default=True, help_text='Whether clearance of this fee is required to unlock exam hall tickets')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Fee Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(default='2025-2026', max_length=50)),
                ('branch', models.CharField(default='ALL', max_length=50)),
                ('year', models.IntegerField(default=1)),
                ('semester', models.IntegerField(default=1)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fee_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='fees.feecategory')),
            ],
            options={
                'ordering': ['academic_year', 'year', 'semester', 'fee_category'],
            },
        ),
        migrations.CreateModel(
            name='StudentFeeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(default='2025-2026', max_length=50)),
                ('year', models.IntegerField(default=1)),
                ('semester', models.IntegerField(default=1)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PAID', 'Fully Paid'), ('PARTIAL', 'Partially Paid'), ('PENDING', 'Payment Pending'), ('OVERDUE', 'Payment Overdue')], default='PENDING', max_length=20)),
                ('is_cleared_for_exam', models.BooleanField(default=False, help_text='Examination clearance / No-Dues certificate status')),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('clearance_remarks', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cleared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleared_fee_records', to=settings.AUTH_USER_MODEL)),
                ('fee_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_fee_records', to='fees.feecategory')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_records', to='students.student')),
            ],
            options={
                'ordering': ['-academic_year', 'student__roll_no', 'fee_category'],
                'unique_together': {('student', 'fee_category', 'academic_year', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(blank=True, max_length=64, unique=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('UPI', 'UPI / QR Payment'), ('NET_BANKING', 'Internet Banking / NEFT / RTGS'), ('CARD', 'Credit / Debit Card'), ('CASH', 'Cash Counter'), ('CHEQUE', 'Cheque / Demand Draft')], default='UPI', max_length=30)),
                ('transaction_reference', models.CharField(blank=True, default='', help_text='UPI UTR number, bank transaction ID, or cheque number', max_length=100)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_fee_payments', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_payments', to='students.student')),
                ('fee_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='fees.studentfeerecord')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
    ]
