# Generated by Django 6.0.7 on 2026-09-27 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeePaymentSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upi_id', models.CharField(default='bursar.spec@ybl', help_text='PhonePe UPI ID / VPA', max_length=100)),
                ('payee_name', models.CharField(default="St. Peter's Engineering College Accounts", max_length=150)),
                ('merchant_code', models.CharField(blank=True, default='', max_length=50)),
                ('custom_qr_image', models.TextField(blank=True, default='', help_text='Optional base64 or URL for static PhonePe QR')),
                ('instructions', models.TextField(blank=True, default='Scan with PhonePe, Google Pay, or Paytm. Enter the 12-digit UTR/UPI Transaction ID to clear dues immediately.')),
                ('auto_clear_on_utr', models.BooleanField(default=True, help_text='Automatically clear fee balance when student submits UTR')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
