# Generated by Django 6.0.7 on 2026-09-27 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_feepaymentsetting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified & Confirmed'), ('REJECTED', 'Rejected')], default='VERIFIED', help_text='Verification status: PENDING, VERIFIED, or REJECTED', max_length=20),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_fee_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feepaymentsetting',
            name='require_verification',
            field=models.BooleanField(default=True, help_text='Require bursar verification before clearing dues (Default True: only cleared after accepting)'),
        ),
        migrations.AlterField(
            model_name='feepaymentsetting',
            name='auto_clear_on_utr',
            field=models.BooleanField(default=False, help_text='Automatically clear fee balance when student submits UTR without bursar review'),
        ),
        migrations.AlterField(
            model_name='feepaymentsetting',
            name='instructions',
            field=models.TextField(blank=True, default='Scan with PhonePe, Google Pay, or Paytm. Enter the 12-digit UTR/UPI Transaction ID to submit for Bursar verification.'),
        ),
    ]
