# Generated by Django 6.0.7 on 2026-09-23 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
        ('students', '0005_academicclass_branch_department_student_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='academic_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='students.academicclass'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='branch',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='announcement',
            name='section',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='announcement',
            name='semester',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='announcement',
            name='target_audience',
            field=models.CharField(choices=[('ALL', 'All Students'), ('BRANCH', 'Branch / Department'), ('YEAR', 'Academic Year'), ('SEMESTER', 'Semester'), ('SECTION', 'Section'), ('CLASS', 'Specific Cohort / Class')], default='ALL', max_length=20),
        ),
        migrations.AddField(
            model_name='announcement',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
