# Generated by Django 6.0.7 on 2026-09-22 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('STUDENT_CREATE', 'Student Created'), ('STUDENT_UPDATE', 'Student Updated'), ('STUDENT_DEACTIVATE', 'Student Deactivated'), ('STUDENT_ACTIVATE', 'Student Restored'), ('ATTENDANCE_SESSION_START', 'Attendance Session Started'), ('ATTENDANCE_QR_MARK', 'QR Attendance Marked'), ('ATTENDANCE_BULK_SAVE', 'Bulk Attendance Saved'), ('MARKS_UPDATE', 'Marks Updated'), ('ANNOUNCEMENT_CREATE', 'Announcement Created'), ('USER_CREATE', 'User Created')], max_length=40)),
                ('entity', models.CharField(max_length=50)),
                ('entity_id', models.CharField(blank=True, default='', max_length=50)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
