# Generated by Django 6.0.7 on 2026-10-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('STUDENT_CREATE', 'Student Created'), ('STUDENT_UPDATE', 'Student Updated'), ('STUDENT_DEACTIVATE', 'Student Deactivated'), ('STUDENT_ACTIVATE', 'Student Restored'), ('ATTENDANCE_SESSION_START', 'Attendance Session Started'), ('ATTENDANCE_SESSION_CLOSE', 'Attendance Session Closed'), ('ATTENDANCE_QR_MARK', 'QR Attendance Marked'), ('ATTENDANCE_BULK_SAVE', 'Bulk Attendance Saved'), ('MARKS_UPDATE', 'Marks Updated'), ('ANNOUNCEMENT_CREATE', 'Announcement Created'), ('ANNOUNCEMENT_DELETE', 'Announcement Deactivated'), ('REPORT_GENERATE', 'Report Generated'), ('USER_CREATE', 'User Created'), ('TEACHER_CREATE', 'Teacher Created'), ('TIMETABLE_CREATE', 'Timetable Slot Created'), ('TIMETABLE_UPDATE', 'Timetable Slot Updated'), ('TIMETABLE_DELETE', 'Timetable Slot Deleted'), ('ACADEMIC_SETUP', 'Academic Structure Modified')], max_length=40),
        ),
    ]
