# Generated by Django 6.0.7 on 2026-10-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('STUDENT_CREATE', 'Student Created'), ('STUDENT_UPDATE', 'Student Updated'), ('STUDENT_DEACTIVATE', 'Student Deactivated'), ('STUDENT_ACTIVATE', 'Student Restored'), ('ATTENDANCE_SESSION_START', 'Attendance Session Started'), ('ATTENDANCE_SESSION_CLOSE', 'Attendance Session Closed'), ('ATTENDANCE_QR_MARK', 'QR Attendance Marked'), ('ATTENDANCE_BULK_SAVE', 'Bulk Attendance Saved'), ('MARKS_UPDATE', 'Marks Updated'), ('ANNOUNCEMENT_CREATE', 'Announcement Created'), ('ANNOUNCEMENT_DELETE', 'Announcement Deactivated'), ('REPORT_GENERATE', 'Report Generated'), ('USER_CREATE', 'User Created'), ('TEACHER_CREATE', 'Teacher Created'), ('TIMETABLE_CREATE', 'Timetable Slot Created'), ('TIMETABLE_UPDATE', 'Timetable Slot Updated'), ('TIMETABLE_DELETE', 'Timetable Slot Deleted'), ('ACADEMIC_SETUP', 'Academic Structure Modified'), ('LOGIN_FAILED', 'Failed Login Attempt'), ('LOGIN_LOCKOUT', 'Account Lockout Triggered'), ('PASSWORD_CHANGE', 'Password Changed'), ('STUDENT_ACCOUNT_ACTIVATE', 'Student Account Activated'), ('ACTIVATION_TOKEN_REQUEST', 'Activation Token Requested'), ('PROXY_ATTEMPT_FLAGGED', 'Proxy Attendance Flagged'), ('UNAUTHORIZED_ACCESS_BLOCKED', 'Unauthorized Access Blocked')], max_length=50),
        ),
    ]
